services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./Data_Layer/initdb:/docker-entrypoint-initdb.d
    networks:
      - minha-rede-spark
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gis"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  jupyter_data:
  jupyter_runtime:
  postgis_data:

networks:
  minha-rede-spark:
    driver: bridge
